name       : python-setuptools-scm-git-archive
version    : '1.2'
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/s/setuptools_scm_git_archive/setuptools_scm_git_archive-1.2.tar.gz : 92e8149c1f4a62fe170962b4ff8cb3d53bfa90fc944f1f1758cebaef56a67f13
homepage   : https://pypi.org/project/setuptools-scm-git-archive/
license    : MIT
component  : programming.python
summary    : setuptools_scm plugin for git archives
description: |
    This is a setuptools_scm plugin that adds support for git archives (for example the ones GitHub automatically generates).
builddeps  :
    - python-setuptools-scm
rundeps    :
    - python-setuptools-scm
build      : |
    %python3_setup
install    : |
    %python3_install
